### PR TITLE
adapt to latest ex-aws

### LINKED ISSUE #24: CaseClauseError  for InvalidSequenceTokenException with ex_aws 2.2.4
👋

I'm getting

```elixir
CaseClauseError: no case clause matching: {:error, {"InvalidSequenceTokenException", "The given sequenceToken is invalid. The next expected sequenceToken is: 49619543027323424921201786257049013329532568378470856290", "49619543027323424921201786257049013329532568378470856290"}}
  File "lib/cloud_watch/aws_proxy.ex", line 124, in CloudWatch.AwsProxy.request/2
  File "lib/cloud_watch.ex", line 186, in CloudWatch.do_flush/4
  File "lib/cloud_watch.ex", line 47, in CloudWatch.handle_info/2
  File "gen_event.erl", line 627, in :gen_event.server_update/4
  File "gen_event.erl", line 609, in :gen_event.server_notify/4
  File "gen_event.erl", line 398, in :gen_event.handle_msg/6
  File "proc_lib.erl", line 226, in :proc_lib.init_p_do_apply/3
```

since the match in `CloudWatch.AwsProxy.request/2` expects `{:error, {type, info}}` and `{:error, {type, into, sequenceToken}}` is returned from ex_aws.

I'm using `ex_aws 2.2.4` that was recently released.

Fix: https://github.com/heyoutline/cloud_watch/pull/25

### PR DESCRIPTION
**Pull request by ruslandoga**
closes #24

### CODE REVIEW

**Comment by kuiro5** [comment]
Thanks for the PR. Looks good, mind adding a quick test?

File: test/cloud_watch_test.exs [hunk 1]
```diff
@@ -10,7 +10,7 @@ defmodule CloudWatchTest do
   use ExUnit.Case, async: false
 
   setup_all do
-    {:ok, _} = Cycler.start_link()
```
Comment (ruslandoga) [inline test/cloud_watch_test.exs:13]: When I ran tests locally this was failing here or in log_stream_name_test depending which ran first since cycler doesn't exit after the test ends.

File: test/cloud_watch_test.exs [hunk 2]
```diff
@@ -10,7 +10,7 @@ defmodule CloudWatchTest do
...
+    start_supervised(Cycler)
```
Comment (ruslandoga) [inline test/cloud_watch_test.exs:13]: This is the fix for the above.

**Comment by ruslandoga** [comment]
@kuiro5 I've added a test.

**Comment by ruslandoga** [comment]
@kuiro5 hi, sorry to bother again. I wonder if it would be possible to cut a release for current master?

**Comment by ruslandoga** [comment]
@kuiro5 ping?

**Comment by kuiro5** [comment]
@ruslandoga @msmithstubbs v0.4.1 released, apologies on the delay.
